name: Test Container Env
on:
  workflow_dispatch:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
      - name: Dump Important folders value
        run: |
          echo "github.workspace=${{ github.workspace }}"
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          echo "runner.temp=${{ runner.temp }}"
          echo "RUNNER_TEMP=${RUNNER_TEMP}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Dump Runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "${RUNNER_CONTEXT}"

      - name: test env context
        run: echo ${{ env.RUNNER_TEMP }}

      - name: create test file
        run: echo "Test File" > "${RUNNER_TEMP}/log.txt"

      - name: upload test file
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          if-no-files-found: error
          path: |
            ${{env.RUNNER_TEMP}}/log.txt
